apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: integreatly-operator
rules:
    -
        apiGroups:
            - applicationmonitoring.integreatly.org
        resources:
            - applicationmonitorings
            - blackboxtargets
        verbs:
            - get
            - create
            - update
            - list
    -
        apiGroups:
            - batch
        resources:
            - cronjobs
        verbs:
            - create
            - update
    -
        apiGroups:
            - rbac.authorization.k8s.io
        resources:
            - clusterroles
            - clusterrolebindings
        verbs:
            - create
            - update
    -
        apiGroups:
            - '*'
        resources:
            - '*'
        verbs:
            - get
            - list
    -
        apiGroups:
            - ""
        resources:
            - pods/exec
        verbs:
            - create
            - update
    -
        apiGroups:
            - integreatly.org
        resources:
            - '*'
        verbs:
            - '*'
    -
        apiGroups:
            - ""
        resources:
            - namespaces
            - namespaces/finalizers
            - serviceaccounts
        verbs:
            - list
            - create
            - watch
            - get
            - update
    -
        apiGroups:
            - operators.coreos.com
        resources:
            - catalogsourceconfigs
        verbs:
            - list
            - create
            - watch
            - delete
    -
        apiGroups:
            - ""
        resources:
            - pods
            - secrets
        verbs:
            - list
            - get
    -
        apiGroups:
            - operators.coreos.com
        resources:
            - catalogsourceconfigs/finalizers
        verbs:
            - '*'
    -
        apiGroups:
            - operators.coreos.com
        resources:
            - operatorgroups
            - subscriptions
            - installplans
        verbs:
            - list
            - create
            - watch
            - get
            - delete
            - update
    -
        apiGroups:
            - aerogear.org
        resources:
            - keycloaks
            - keycloakrealms
        verbs:
            - list
            - create
            - update
            - watch
            - get
    -
        apiGroups:
            - kafka.strimzi.io
        resources:
            - kafkas
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - apps.3scale.net
        resources:
            - apimanagers
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - org.eclipse.che
        resources:
            - checlusters
            - checlusters/finalizers
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - syndesis.io
        resources:
            - syndesises
            - syndesises/finalizers
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - admin.enmasse.io
        resources:
            - authenticationservices
            - addressplans
            - addressspaceplans
            - brokeredinfraconfigs
            - standardinfraconfigs
            - consoleservices
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - oauth.openshift.io
        resources:
            - oauthclients
        verbs:
            - create
            - get
            - update
            - delete
    -
        apiGroups:
            - ""
        resources:
            - configmaps
        verbs:
            - get
            - update
    -
        apiGroups:
            - apps.openshift.io
        resources:
            - deploymentconfigs/instantiate
            - deploymentconfigs
        verbs:
            - create
            - update
    -
        apiGroups:
            - ""
        resources:
            - secrets
        verbs:
            - get
            - create
            - update
    -
        apiGroups:
            - gpte.opentlc.com
        resources:
            - nexus
        verbs:
            - list
            - create
            - watch
            - get
    -
        apiGroups:
            - launcher.fabric8.io
        resources:
            - launchers
        verbs:
            - get
            - create
    -
        apiGroups:
            - rbac.authorization.k8s.io
        resources:
            - rolebindings
        verbs:
            - create
            - update
    -
        apiGroups:
            - user.openshift.io
        resources:
            - users
        verbs:
            - watch
    -
        apiGroups:
            - user.openshift.io
        resources:
            - groups
        verbs:
            - get
            - create
            - update
    -
        apiGroups:
            - samples.operator.openshift.io
        resources:
            - configs
        verbs:
            - get
            - update
    -
        apiGroups:
            - image.openshift.io
        resources:
            - imagestreams
        verbs:
            - get
            - create
            - delete
    -
        apiGroups:
            - template.openshift.io
        resources:
            - templates
        verbs:
            - get
            - create
            - delete
    -
        apiGroups:
            - push.aerogear.org
        resources:
            - unifiedpushservers
        verbs:
            - get
            - create
    -
        apiGroups:
            - mobile-security-service.aerogear.org
        resources:
            - '*'
        verbs:
            - get
            - list
            - watch
            - update
            - create
    -
        apiGroups:
            - mdc.aerogear.org
        resources:
            - '*'
        verbs:
            - get
            - list
            - watch
            - update
            - create
